#ifdef __cplusplus
 extern "C" {
 #endif

#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#include "utility.h"

struct sConfiguration {
	int log_usage;
} configuration;

// BEGIN - GENERATED BY C-UPDATE-HEADER
void configuration_init();
void configuration_parse_commandline(int argc, char **argv);
const char *configuration_get_string(const char *name, const char *default_value);
int configuration_get_int(const char *name, int default_value);
int configuration_get_bool(const char *name, int default_value);
double configuration_get_double(const char *name, double default_value);
// END - GENERATED BY C-UPDATE-HEADER

#endif

#ifdef __cplusplus
 }
 #endif
