#ifndef ENVIRONMENT_H
#define ENVIRONMENT_H

#include "utility.h"
#include <stdio.h>

// Environment structure
struct sEnvironment {
	struct {
		int width;
		int height;
		int length;	
	} arena;

	struct {
		struct {
			double x1;
			double y1;
			double x2;
			double y2;
		} item[32];
		int count;
	} lines;

	struct {
		struct {
			double x1;
			double y1;
			double x2;
			double y2;
		} item[32];
		int count;
	} rectangles;
};

// BEGIN - GENERATED BY C-UPDATE-HEADER
// Initializes the environment.
void environment_init(struct sEnvironment *environment,int,int,int);
// Adds a line.
void environment_lines_add(struct sEnvironment *environment, double x1, double y1, double x2, double y2);
// Adds a rectangle.
void environment_rectangles_add(struct sEnvironment *environment, double x1, double y1, double x2, double y2);
// Returns whether a point (world coordinates) is valid or not.
int environment_position_valid(struct sEnvironment *environment, double x, double y, double z);
// END - GENERATED BY C-UPDATE-HEADER

#endif

