#ifndef FLOW_H
#define FLOW_H

#include "utility.h"
#include "flow.h"
#include <stdio.h>


//#define FLOW_MAX_COUNT_X 81
//#define FLOW_MAX_COUNT_Y 21
//#define FLOW_MAX_COUNT_Z 11


//#define FLOW_MAX_COUNT_X 2211
//#define FLOW_MAX_COUNT_Y 42
//#define FLOW_MAX_COUNT_Z 12


//#define FLOW_MAX_COUNT_X 61 //
//#define FLOW_MAX_COUNT_Y 21
//#define FLOW_MAX_COUNT_Z 6

struct sFlow {
	struct {
		int x;
		int y;
		int z;
	} cells_count;
	struct {
		double x;
		double y;
		double z;
	} cells_size;
	
	double ***u;
	double ***v;
	double ***w;
	//double u[FLOW_MAX_COUNT_X][FLOW_MAX_COUNT_Y][FLOW_MAX_COUNT_Z];
	//double w[FLOW_MAX_COUNT_X][FLOW_MAX_COUNT_Y][FLOW_MAX_COUNT_Z];
	//double v[FLOW_MAX_COUNT_X][FLOW_MAX_COUNT_Y][FLOW_MAX_COUNT_Z];//3d
	int			max_x;
	int			max_y;
	int			max_z;
	double		max_count_x;
	double		max_count_y;
	double		max_count_z;
	struct {
		double u;
		double w;
		double v; //3d
	} result;
};



// BEGIN - GENERATED BY C-UPDATE-HEADER
// Initialize the flow structure
void flow_init(struct sFlow *flow,int,int,int,double);
void flow_set_uniform(struct sFlow *flow, double u, double v, double w); //3d
void flow_set_fancy(struct sFlow *flow);
void flow_read(struct sFlow *flow, char *file_u, char *file_v, char *file_w, int flagFirstTime); //3d
void flow_get(struct sFlow *flow, double x, double y, double z);//3d
double*** arr3dAlloc(const int ind1, const int ind2, const int ind3);


// END - GENERATED BY C-UPDATE-HEADER

#endif
