#ifdef __cplusplus
 extern "C" {
 #endif

#ifndef UTILITY_H
#define UTILITY_H

// General
#define PI 3.14159265358979

struct sPoint {
	float x;
	float y;
};

struct sPointInt {
	int x;
	int y;
};

// BEGIN - GENERATED BY C-UPDATE-HEADER
// Returns the minimum of two values
int mini(int value1, int value2);
// Returns the minimum of two values
double mind(double value1, double value2);
// Returns the maximum of two values
int maxi(int value1, int value2);
// Returns the maximum of two values
double maxd(double value1, double value2);
// Returns the factorial.
int factorial(int x);
// Returns P(X=x) if X~Poisson(lambda).
double poisson_pdf(double lambda, double x);
// Returns a sample of X if X~Poisson(lambda) estimated with n trials.
int poisson_random(double lambda, int n);
// Start the timer.
void timer_start();
// Stops the timer and prints the elapsed time.
void timer_stop(const char *label);
// END - GENERATED BY C-UPDATE-HEADER

#endif

#ifdef __cplusplus
 }
 #endif
