"""autogenerated by genmsg_py from readings.msg. Do not edit."""
import roslib.message
import struct


class readings(roslib.message.Message):
  _md5sum = "db1beda0b3344f27d34da8b04c42f334"
  _type = "fake_MOX/readings"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 r0_id
float64 r0_x
float64 r0_y
float64 r0_z
float64 r0_val
float64 r1_id
float64 r1_x
float64 r1_y
float64 r1_z
float64 r1_val
float64 r2_id
float64 r2_x
float64 r2_y
float64 r2_z
float64 r2_val
float64 r3_val
float64 r4_val
float64 r5_val
float64 r6_val
float64 r7_val
float64 r8_val
float64 r9_val
float64 r10_val
float64 r11_val
float64 r12_val
float64 r13_val
float64 r14_val
float64 r15_val
float64 r16_val
float64 r17_val
float64 r18_val
float64 r19_val
float64 r20_val
float64 r21_val
float64 r22_val
float64 r23_val
float64 r24_val
float64 r25_val
float64 r26_val
float64 r27_val
float64 r28_val
float64 r29_val
float64 r30_val
float64 r31_val
float64 r32_val
float64 r33_val
float64 r34_val
float64 r35_val
float64 r36_val
float64 r37_val
float64 r38_val
float64 r39_val
float64 r40_val
float64 r41_val
float64 r42_val
float64 r43_val
float64 r44_val
float64 r45_val
float64 r46_val
float64 r47_val
float64 r48_val
float64 r49_val
float64 r50_val
float64 r51_val
float64 r52_val
float64 r53_val
float64 r54_val
float64 r55_val
float64 r56_val
float64 r57_val
float64 r58_val
float64 r59_val
float64 r60_val
float64 r61_val
float64 r62_val
float64 r63_val
float64 r64_val
float64 r65_val
float64 r66_val
float64 r67_val
float64 r68_val
float64 r69_val
float64 r70_val
float64 r71_val
float64 r72_val
float64 r73_val
float64 r74_val
float64 r75_val
float64 r76_val
float64 r77_val
float64 r78_val
float64 r79_val
float64 r80_val
float64 r81_val
float64 r82_val
float64 r83_val
float64 r0_con
float64 r1_con
float64 r2_con

"""
  __slots__ = ['r0_id','r0_x','r0_y','r0_z','r0_val','r1_id','r1_x','r1_y','r1_z','r1_val','r2_id','r2_x','r2_y','r2_z','r2_val','r3_val','r4_val','r5_val','r6_val','r7_val','r8_val','r9_val','r10_val','r11_val','r12_val','r13_val','r14_val','r15_val','r16_val','r17_val','r18_val','r19_val','r20_val','r21_val','r22_val','r23_val','r24_val','r25_val','r26_val','r27_val','r28_val','r29_val','r30_val','r31_val','r32_val','r33_val','r34_val','r35_val','r36_val','r37_val','r38_val','r39_val','r40_val','r41_val','r42_val','r43_val','r44_val','r45_val','r46_val','r47_val','r48_val','r49_val','r50_val','r51_val','r52_val','r53_val','r54_val','r55_val','r56_val','r57_val','r58_val','r59_val','r60_val','r61_val','r62_val','r63_val','r64_val','r65_val','r66_val','r67_val','r68_val','r69_val','r70_val','r71_val','r72_val','r73_val','r74_val','r75_val','r76_val','r77_val','r78_val','r79_val','r80_val','r81_val','r82_val','r83_val','r0_con','r1_con','r2_con']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       r0_id,r0_x,r0_y,r0_z,r0_val,r1_id,r1_x,r1_y,r1_z,r1_val,r2_id,r2_x,r2_y,r2_z,r2_val,r3_val,r4_val,r5_val,r6_val,r7_val,r8_val,r9_val,r10_val,r11_val,r12_val,r13_val,r14_val,r15_val,r16_val,r17_val,r18_val,r19_val,r20_val,r21_val,r22_val,r23_val,r24_val,r25_val,r26_val,r27_val,r28_val,r29_val,r30_val,r31_val,r32_val,r33_val,r34_val,r35_val,r36_val,r37_val,r38_val,r39_val,r40_val,r41_val,r42_val,r43_val,r44_val,r45_val,r46_val,r47_val,r48_val,r49_val,r50_val,r51_val,r52_val,r53_val,r54_val,r55_val,r56_val,r57_val,r58_val,r59_val,r60_val,r61_val,r62_val,r63_val,r64_val,r65_val,r66_val,r67_val,r68_val,r69_val,r70_val,r71_val,r72_val,r73_val,r74_val,r75_val,r76_val,r77_val,r78_val,r79_val,r80_val,r81_val,r82_val,r83_val,r0_con,r1_con,r2_con
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(readings, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.r0_id is None:
        self.r0_id = 0.
      if self.r0_x is None:
        self.r0_x = 0.
      if self.r0_y is None:
        self.r0_y = 0.
      if self.r0_z is None:
        self.r0_z = 0.
      if self.r0_val is None:
        self.r0_val = 0.
      if self.r1_id is None:
        self.r1_id = 0.
      if self.r1_x is None:
        self.r1_x = 0.
      if self.r1_y is None:
        self.r1_y = 0.
      if self.r1_z is None:
        self.r1_z = 0.
      if self.r1_val is None:
        self.r1_val = 0.
      if self.r2_id is None:
        self.r2_id = 0.
      if self.r2_x is None:
        self.r2_x = 0.
      if self.r2_y is None:
        self.r2_y = 0.
      if self.r2_z is None:
        self.r2_z = 0.
      if self.r2_val is None:
        self.r2_val = 0.
      if self.r3_val is None:
        self.r3_val = 0.
      if self.r4_val is None:
        self.r4_val = 0.
      if self.r5_val is None:
        self.r5_val = 0.
      if self.r6_val is None:
        self.r6_val = 0.
      if self.r7_val is None:
        self.r7_val = 0.
      if self.r8_val is None:
        self.r8_val = 0.
      if self.r9_val is None:
        self.r9_val = 0.
      if self.r10_val is None:
        self.r10_val = 0.
      if self.r11_val is None:
        self.r11_val = 0.
      if self.r12_val is None:
        self.r12_val = 0.
      if self.r13_val is None:
        self.r13_val = 0.
      if self.r14_val is None:
        self.r14_val = 0.
      if self.r15_val is None:
        self.r15_val = 0.
      if self.r16_val is None:
        self.r16_val = 0.
      if self.r17_val is None:
        self.r17_val = 0.
      if self.r18_val is None:
        self.r18_val = 0.
      if self.r19_val is None:
        self.r19_val = 0.
      if self.r20_val is None:
        self.r20_val = 0.
      if self.r21_val is None:
        self.r21_val = 0.
      if self.r22_val is None:
        self.r22_val = 0.
      if self.r23_val is None:
        self.r23_val = 0.
      if self.r24_val is None:
        self.r24_val = 0.
      if self.r25_val is None:
        self.r25_val = 0.
      if self.r26_val is None:
        self.r26_val = 0.
      if self.r27_val is None:
        self.r27_val = 0.
      if self.r28_val is None:
        self.r28_val = 0.
      if self.r29_val is None:
        self.r29_val = 0.
      if self.r30_val is None:
        self.r30_val = 0.
      if self.r31_val is None:
        self.r31_val = 0.
      if self.r32_val is None:
        self.r32_val = 0.
      if self.r33_val is None:
        self.r33_val = 0.
      if self.r34_val is None:
        self.r34_val = 0.
      if self.r35_val is None:
        self.r35_val = 0.
      if self.r36_val is None:
        self.r36_val = 0.
      if self.r37_val is None:
        self.r37_val = 0.
      if self.r38_val is None:
        self.r38_val = 0.
      if self.r39_val is None:
        self.r39_val = 0.
      if self.r40_val is None:
        self.r40_val = 0.
      if self.r41_val is None:
        self.r41_val = 0.
      if self.r42_val is None:
        self.r42_val = 0.
      if self.r43_val is None:
        self.r43_val = 0.
      if self.r44_val is None:
        self.r44_val = 0.
      if self.r45_val is None:
        self.r45_val = 0.
      if self.r46_val is None:
        self.r46_val = 0.
      if self.r47_val is None:
        self.r47_val = 0.
      if self.r48_val is None:
        self.r48_val = 0.
      if self.r49_val is None:
        self.r49_val = 0.
      if self.r50_val is None:
        self.r50_val = 0.
      if self.r51_val is None:
        self.r51_val = 0.
      if self.r52_val is None:
        self.r52_val = 0.
      if self.r53_val is None:
        self.r53_val = 0.
      if self.r54_val is None:
        self.r54_val = 0.
      if self.r55_val is None:
        self.r55_val = 0.
      if self.r56_val is None:
        self.r56_val = 0.
      if self.r57_val is None:
        self.r57_val = 0.
      if self.r58_val is None:
        self.r58_val = 0.
      if self.r59_val is None:
        self.r59_val = 0.
      if self.r60_val is None:
        self.r60_val = 0.
      if self.r61_val is None:
        self.r61_val = 0.
      if self.r62_val is None:
        self.r62_val = 0.
      if self.r63_val is None:
        self.r63_val = 0.
      if self.r64_val is None:
        self.r64_val = 0.
      if self.r65_val is None:
        self.r65_val = 0.
      if self.r66_val is None:
        self.r66_val = 0.
      if self.r67_val is None:
        self.r67_val = 0.
      if self.r68_val is None:
        self.r68_val = 0.
      if self.r69_val is None:
        self.r69_val = 0.
      if self.r70_val is None:
        self.r70_val = 0.
      if self.r71_val is None:
        self.r71_val = 0.
      if self.r72_val is None:
        self.r72_val = 0.
      if self.r73_val is None:
        self.r73_val = 0.
      if self.r74_val is None:
        self.r74_val = 0.
      if self.r75_val is None:
        self.r75_val = 0.
      if self.r76_val is None:
        self.r76_val = 0.
      if self.r77_val is None:
        self.r77_val = 0.
      if self.r78_val is None:
        self.r78_val = 0.
      if self.r79_val is None:
        self.r79_val = 0.
      if self.r80_val is None:
        self.r80_val = 0.
      if self.r81_val is None:
        self.r81_val = 0.
      if self.r82_val is None:
        self.r82_val = 0.
      if self.r83_val is None:
        self.r83_val = 0.
      if self.r0_con is None:
        self.r0_con = 0.
      if self.r1_con is None:
        self.r1_con = 0.
      if self.r2_con is None:
        self.r2_con = 0.
    else:
      self.r0_id = 0.
      self.r0_x = 0.
      self.r0_y = 0.
      self.r0_z = 0.
      self.r0_val = 0.
      self.r1_id = 0.
      self.r1_x = 0.
      self.r1_y = 0.
      self.r1_z = 0.
      self.r1_val = 0.
      self.r2_id = 0.
      self.r2_x = 0.
      self.r2_y = 0.
      self.r2_z = 0.
      self.r2_val = 0.
      self.r3_val = 0.
      self.r4_val = 0.
      self.r5_val = 0.
      self.r6_val = 0.
      self.r7_val = 0.
      self.r8_val = 0.
      self.r9_val = 0.
      self.r10_val = 0.
      self.r11_val = 0.
      self.r12_val = 0.
      self.r13_val = 0.
      self.r14_val = 0.
      self.r15_val = 0.
      self.r16_val = 0.
      self.r17_val = 0.
      self.r18_val = 0.
      self.r19_val = 0.
      self.r20_val = 0.
      self.r21_val = 0.
      self.r22_val = 0.
      self.r23_val = 0.
      self.r24_val = 0.
      self.r25_val = 0.
      self.r26_val = 0.
      self.r27_val = 0.
      self.r28_val = 0.
      self.r29_val = 0.
      self.r30_val = 0.
      self.r31_val = 0.
      self.r32_val = 0.
      self.r33_val = 0.
      self.r34_val = 0.
      self.r35_val = 0.
      self.r36_val = 0.
      self.r37_val = 0.
      self.r38_val = 0.
      self.r39_val = 0.
      self.r40_val = 0.
      self.r41_val = 0.
      self.r42_val = 0.
      self.r43_val = 0.
      self.r44_val = 0.
      self.r45_val = 0.
      self.r46_val = 0.
      self.r47_val = 0.
      self.r48_val = 0.
      self.r49_val = 0.
      self.r50_val = 0.
      self.r51_val = 0.
      self.r52_val = 0.
      self.r53_val = 0.
      self.r54_val = 0.
      self.r55_val = 0.
      self.r56_val = 0.
      self.r57_val = 0.
      self.r58_val = 0.
      self.r59_val = 0.
      self.r60_val = 0.
      self.r61_val = 0.
      self.r62_val = 0.
      self.r63_val = 0.
      self.r64_val = 0.
      self.r65_val = 0.
      self.r66_val = 0.
      self.r67_val = 0.
      self.r68_val = 0.
      self.r69_val = 0.
      self.r70_val = 0.
      self.r71_val = 0.
      self.r72_val = 0.
      self.r73_val = 0.
      self.r74_val = 0.
      self.r75_val = 0.
      self.r76_val = 0.
      self.r77_val = 0.
      self.r78_val = 0.
      self.r79_val = 0.
      self.r80_val = 0.
      self.r81_val = 0.
      self.r82_val = 0.
      self.r83_val = 0.
      self.r0_con = 0.
      self.r1_con = 0.
      self.r2_con = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_99d.pack(_x.r0_id, _x.r0_x, _x.r0_y, _x.r0_z, _x.r0_val, _x.r1_id, _x.r1_x, _x.r1_y, _x.r1_z, _x.r1_val, _x.r2_id, _x.r2_x, _x.r2_y, _x.r2_z, _x.r2_val, _x.r3_val, _x.r4_val, _x.r5_val, _x.r6_val, _x.r7_val, _x.r8_val, _x.r9_val, _x.r10_val, _x.r11_val, _x.r12_val, _x.r13_val, _x.r14_val, _x.r15_val, _x.r16_val, _x.r17_val, _x.r18_val, _x.r19_val, _x.r20_val, _x.r21_val, _x.r22_val, _x.r23_val, _x.r24_val, _x.r25_val, _x.r26_val, _x.r27_val, _x.r28_val, _x.r29_val, _x.r30_val, _x.r31_val, _x.r32_val, _x.r33_val, _x.r34_val, _x.r35_val, _x.r36_val, _x.r37_val, _x.r38_val, _x.r39_val, _x.r40_val, _x.r41_val, _x.r42_val, _x.r43_val, _x.r44_val, _x.r45_val, _x.r46_val, _x.r47_val, _x.r48_val, _x.r49_val, _x.r50_val, _x.r51_val, _x.r52_val, _x.r53_val, _x.r54_val, _x.r55_val, _x.r56_val, _x.r57_val, _x.r58_val, _x.r59_val, _x.r60_val, _x.r61_val, _x.r62_val, _x.r63_val, _x.r64_val, _x.r65_val, _x.r66_val, _x.r67_val, _x.r68_val, _x.r69_val, _x.r70_val, _x.r71_val, _x.r72_val, _x.r73_val, _x.r74_val, _x.r75_val, _x.r76_val, _x.r77_val, _x.r78_val, _x.r79_val, _x.r80_val, _x.r81_val, _x.r82_val, _x.r83_val, _x.r0_con, _x.r1_con, _x.r2_con))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 792
      (_x.r0_id, _x.r0_x, _x.r0_y, _x.r0_z, _x.r0_val, _x.r1_id, _x.r1_x, _x.r1_y, _x.r1_z, _x.r1_val, _x.r2_id, _x.r2_x, _x.r2_y, _x.r2_z, _x.r2_val, _x.r3_val, _x.r4_val, _x.r5_val, _x.r6_val, _x.r7_val, _x.r8_val, _x.r9_val, _x.r10_val, _x.r11_val, _x.r12_val, _x.r13_val, _x.r14_val, _x.r15_val, _x.r16_val, _x.r17_val, _x.r18_val, _x.r19_val, _x.r20_val, _x.r21_val, _x.r22_val, _x.r23_val, _x.r24_val, _x.r25_val, _x.r26_val, _x.r27_val, _x.r28_val, _x.r29_val, _x.r30_val, _x.r31_val, _x.r32_val, _x.r33_val, _x.r34_val, _x.r35_val, _x.r36_val, _x.r37_val, _x.r38_val, _x.r39_val, _x.r40_val, _x.r41_val, _x.r42_val, _x.r43_val, _x.r44_val, _x.r45_val, _x.r46_val, _x.r47_val, _x.r48_val, _x.r49_val, _x.r50_val, _x.r51_val, _x.r52_val, _x.r53_val, _x.r54_val, _x.r55_val, _x.r56_val, _x.r57_val, _x.r58_val, _x.r59_val, _x.r60_val, _x.r61_val, _x.r62_val, _x.r63_val, _x.r64_val, _x.r65_val, _x.r66_val, _x.r67_val, _x.r68_val, _x.r69_val, _x.r70_val, _x.r71_val, _x.r72_val, _x.r73_val, _x.r74_val, _x.r75_val, _x.r76_val, _x.r77_val, _x.r78_val, _x.r79_val, _x.r80_val, _x.r81_val, _x.r82_val, _x.r83_val, _x.r0_con, _x.r1_con, _x.r2_con,) = _struct_99d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_99d.pack(_x.r0_id, _x.r0_x, _x.r0_y, _x.r0_z, _x.r0_val, _x.r1_id, _x.r1_x, _x.r1_y, _x.r1_z, _x.r1_val, _x.r2_id, _x.r2_x, _x.r2_y, _x.r2_z, _x.r2_val, _x.r3_val, _x.r4_val, _x.r5_val, _x.r6_val, _x.r7_val, _x.r8_val, _x.r9_val, _x.r10_val, _x.r11_val, _x.r12_val, _x.r13_val, _x.r14_val, _x.r15_val, _x.r16_val, _x.r17_val, _x.r18_val, _x.r19_val, _x.r20_val, _x.r21_val, _x.r22_val, _x.r23_val, _x.r24_val, _x.r25_val, _x.r26_val, _x.r27_val, _x.r28_val, _x.r29_val, _x.r30_val, _x.r31_val, _x.r32_val, _x.r33_val, _x.r34_val, _x.r35_val, _x.r36_val, _x.r37_val, _x.r38_val, _x.r39_val, _x.r40_val, _x.r41_val, _x.r42_val, _x.r43_val, _x.r44_val, _x.r45_val, _x.r46_val, _x.r47_val, _x.r48_val, _x.r49_val, _x.r50_val, _x.r51_val, _x.r52_val, _x.r53_val, _x.r54_val, _x.r55_val, _x.r56_val, _x.r57_val, _x.r58_val, _x.r59_val, _x.r60_val, _x.r61_val, _x.r62_val, _x.r63_val, _x.r64_val, _x.r65_val, _x.r66_val, _x.r67_val, _x.r68_val, _x.r69_val, _x.r70_val, _x.r71_val, _x.r72_val, _x.r73_val, _x.r74_val, _x.r75_val, _x.r76_val, _x.r77_val, _x.r78_val, _x.r79_val, _x.r80_val, _x.r81_val, _x.r82_val, _x.r83_val, _x.r0_con, _x.r1_con, _x.r2_con))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 792
      (_x.r0_id, _x.r0_x, _x.r0_y, _x.r0_z, _x.r0_val, _x.r1_id, _x.r1_x, _x.r1_y, _x.r1_z, _x.r1_val, _x.r2_id, _x.r2_x, _x.r2_y, _x.r2_z, _x.r2_val, _x.r3_val, _x.r4_val, _x.r5_val, _x.r6_val, _x.r7_val, _x.r8_val, _x.r9_val, _x.r10_val, _x.r11_val, _x.r12_val, _x.r13_val, _x.r14_val, _x.r15_val, _x.r16_val, _x.r17_val, _x.r18_val, _x.r19_val, _x.r20_val, _x.r21_val, _x.r22_val, _x.r23_val, _x.r24_val, _x.r25_val, _x.r26_val, _x.r27_val, _x.r28_val, _x.r29_val, _x.r30_val, _x.r31_val, _x.r32_val, _x.r33_val, _x.r34_val, _x.r35_val, _x.r36_val, _x.r37_val, _x.r38_val, _x.r39_val, _x.r40_val, _x.r41_val, _x.r42_val, _x.r43_val, _x.r44_val, _x.r45_val, _x.r46_val, _x.r47_val, _x.r48_val, _x.r49_val, _x.r50_val, _x.r51_val, _x.r52_val, _x.r53_val, _x.r54_val, _x.r55_val, _x.r56_val, _x.r57_val, _x.r58_val, _x.r59_val, _x.r60_val, _x.r61_val, _x.r62_val, _x.r63_val, _x.r64_val, _x.r65_val, _x.r66_val, _x.r67_val, _x.r68_val, _x.r69_val, _x.r70_val, _x.r71_val, _x.r72_val, _x.r73_val, _x.r74_val, _x.r75_val, _x.r76_val, _x.r77_val, _x.r78_val, _x.r79_val, _x.r80_val, _x.r81_val, _x.r82_val, _x.r83_val, _x.r0_con, _x.r1_con, _x.r2_con,) = _struct_99d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_99d = struct.Struct("<99d")
